version: '3.8'

services:
  # Сервис PostgreSQL
  db:
    image: postgres:15
    container_name: aegis-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-aegis}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend сервис
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aegis-backend
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT:-8000}:8000"

  # Sidecar агент для локального хоста
  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    container_name: aegis-local-agent
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${SIDECAR_PORT:-5000}:5000"

  # Frontend сервис
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aegis-frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://backend:8000/v1
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
    name: aegis-postgres-data 
